### ISSUE TITLE
afro bug

### ISSUE THREAD

**Issue by BeaverPup** [Moya-Games/Omuni-Reborn-Bug-Tacker#3]
**Describe the bug**
Afro uses wrong overlay - looks like a bunch of triangles and squares instead of hair. Also on the left side you can see the characters head. 

**To Reproduce**
Open character creator, select afro. 

**Expected behavior**
Normal looking afro not polygons
**Screenshots**
![image](https://user-images.githubusercontent.com/37950756/143364943-0396467b-dcab-42ea-b140-3bf006d28cde.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version unknown

**Additional context**

**Comment by RayChanDev1** [comment]
fiiiiixed
