### ISSUE TITLE
Nose size / curve clips into eyebrows

### ISSUE THREAD

**Issue by BeaverPup** [Moya-Games/Omuni-Reborn-Bug-Tacker#7]
**Describe the bug**
A high nose size and curve makes the nose and eyebrow textures clip into each other. 

**To Reproduce**
1. Go to character creator
2. Click on head > nose > nose size and nose curve

**Expected behavior**
Nose size should not interfere with eyebrow texture. 
**Screenshots**
https://i.gyazo.com/18d617d69a1c093a621471ca8f8bcf6e.mp4

https://i.gyazo.com/815732fb4c07ba6d12e480547e0f38de.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version N/A

**Additional context**
Only max nose size and curve cause this, having max curve and middle size works fine, as does max size and middle curve. 
Not an issue with female model.

**Comment by supimjoel** [comment]
This can be resolved with limitations being placed on the slider values. @TheRayNoodle this is something that needs to be considered during the creation of min/max slider values for every gender. If you agree i think we can close this out

**Comment by RayChanDev1** [comment]
it doesn't happen with the female (as far as i know so far) and I think may tie into the flickering eyebrow issue as well which could possibly mean it's an issue with the model's setup overall. I will definitely keep an eye out for issues like this when doing the min/max slider values for sure though!
