### ISSUE TITLE
animation bug - feet sliding / gliding around

### ISSUE THREAD

**Issue by BeaverPup** [Moya-Games/Omuni-Reborn-Bug-Tacker#8]
**Describe the bug**
Animation - feet gliding / sliding

**To Reproduce**
1 Launch character creator
2 Look at feet

**Expected behavior**
Feet should stay still when on the floor
**Screenshots**

https://user-images.githubusercontent.com/37950756/143371978-55c805d7-71b5-4b87-b2f1-eaf3a5b80bb8.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version N/A

**Comment by supimjoel** [comment]
@TheRayNoodle i think this is just a bad animation, new animation fixes this.

**Comment by RayChanDev1** [comment]
nope nope it can be fixed by baking the pose in the animation file itself (in unity) I just forget the whole actual process for it

**Comment by supimjoel** [comment]
Ok well i guess this can be assigned to you then?
