### ISSUE TITLE
Eyebrow flicker

### ISSUE THREAD

**Issue by BeaverPup** [Moya-Games/Omuni-Reborn-Bug-Tacker#9]
**Describe the bug**
Characters eyebrows flicker. 
**To Reproduce**
1 Launch character creator
2 Look at characters eyebrows

**Expected behavior**
Eyebrows should not flicker
**Screenshots**

https://user-images.githubusercontent.com/37950756/143371375-abefeaca-6502-470c-87e2-d4736d6b9799.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version N/A

**Additional context**
Most likely a problem with camera distance and/or the anti aliasing
The eyebrows on the female character model do not flicker, it is only an issue with the male model.

**Comment by RayChanDev1** [comment]
Updating DCS to GLIB fixed this issue.
